
# enable app support
APP=1
APP_STACKSIZE=300

VPATH += src/

PROJ_OBJ += information.o
PROJ_OBJ += del_handler.o
PROJ_OBJ += wallfollowing_multiranger_onboard.o
PROJ_OBJ += wall_following_projet3.o
PROJ_OBJ += return_to_base.o
PROJ_OBJ += main_commands.o
PROJ_OBJ += command_master.o
PROJ_OBJ += app_main.o

CRAZYFLIE_BASE=..
include $(CRAZYFLIE_BASE)/Makefile